// Generated by CoffeeScript 1.7.1
(function() {
  var ASYNC, P, TEXT, TRM, TYPES, alert, badge, debug, echo, help, info, log, njs_util, rpr, urge, warn, whisper;

  njs_util = require('util');

  TYPES = require('coffeenode-types');

  TEXT = require('coffeenode-text');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'PIPEDREAMS/examples';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  urge = TRM.get_logger('urge', badge);

  echo = TRM.echo.bind(TRM);

  P = require('./main');

  ASYNC = require('async');

  this.show_throughstream = function() {
    var confluence, start, stop, task_id, tasks, _fn, _i, _len, _ref;
    confluence = P.create_throughstream().pipe(P.remit((function(_this) {
      return function(record, send) {
        var n, task_id;
        if (record != null) {
          task_id = record[0], n = record[1];
          debug(task_id, n);
          return send([task_id, n * 2]);
        }
      };
    })(this))).pipe(P.$show());
    tasks = [];
    stop = 14;
    _ref = [3, 9, 12];
    _fn = (function(_this) {
      return function(task_id, start) {
        return tasks.push(function(handler) {
          var x, _j;
          for (x = _j = start; start <= stop ? _j <= stop : _j >= stop; x = start <= stop ? ++_j : --_j) {
            confluence.write([task_id, x]);
          }
          return handler(null);
        });
      };
    })(this);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      start = _ref[_i];
      task_id = tasks.length;
      _fn(task_id, start);
    }
    ASYNC.parallel(tasks, (function(_this) {
      return function(error) {
        if (error != null) {
          throw error;
        }
        return help('ok');
      };
    })(this));
    return null;
  };

  this.main = function() {
    return this.show_throughstream();
  };

  if (module.parent == null) {
    this.main();
  }

}).call(this);
